spring.datasource.url=jdbc:postgresql://localhost:5433/calculadora_gorjetas
spring.datasource.username=gorjetas
spring.datasource.password=gorjetas123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true